# GET http://localhost:3000/api/v1/product/

// POST

# POST http://localhost:3000/api/v1/auth/register
# Content-Type: application/json



GET http://localhost:3000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0cmFuY2hpY3VvbmcyMTEwMkBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMyIsImlhdCI6MTcxMjE2MDA0MiwiZXhwIjoxNzEyNTkyMDQyfQ.y-V77h7hWBTNsdqapk9BHcTns8HSgtyqtvkVGx1hE4g